import type { TopicContent } from "../topicContent";

export const randomNumbers: TopicContent = {
  topicSlug: "random-numbers",
  explanation: [
    "Random number generation is essential for games, simulations, and security. Python's 'random' module provides functions to generate pseudo-random numbers. You must import the module before using it: import random.",
    "The most important function for GCSE is random.randint(a, b) which generates a random integer between a and b INCLUSIVE. Unlike range(), both endpoints are included. For example, random.randint(1, 6) simulates rolling a dice.",
    "Other useful functions include random.random() which gives a float between 0.0 and 1.0, and random.choice(list) which picks a random item from a list. These are all classified as pseudo-random — generated by an algorithm, not truly random.",
    "The OCR specification (J277 Section 2.2) requires you to use random number generation in programming tasks. Common exam scenarios include dice games, random password generators, and quiz question randomisation."
  ],
  codeExamples: [
    {
      title: "Basic Random Integer — Dice Roll",
      code: `import random

# Random integer between 1 and 6 (inclusive)
dice = random.randint(1, 6)
print(f"You rolled a {dice}!")

# Roll 5 times
for i in range(5):
    roll = random.randint(1, 6)
    print(f"Roll {i+1}: {roll}")`,
      description: "random.randint(1, 6) gives 1, 2, 3, 4, 5, or 6 — both ends included."
    },
    {
      title: "Random Choice from a List",
      code: `import random

colours = ["Red", "Blue", "Green", "Yellow"]
chosen = random.choice(colours)
print(f"Random colour: {chosen}")

# Random word from a list
words = ["python", "computer", "algorithm", "variable"]
word = random.choice(words)
print(f"Your word is: {word}")`,
      description: "random.choice() picks one random item from a list."
    },
    {
      title: "Random Password Generator",
      code: `import random

chars = "abcdefghijklmnopqrstuvwxyz0123456789"
password = ""

for i in range(8):
    password += random.choice(chars)

print(f"Your password: {password}")`,
      description: "A classic OCR exam-style task — generating random strings."
    },
    {
      title: "Number Guessing Game",
      code: `import random

secret = random.randint(1, 100)
guess = 0
attempts = 0

while guess != secret:
    guess = int(input("Guess (1-100): "))
    attempts += 1
    if guess < secret:
        print("Too low!")
    elif guess > secret:
        print("Too high!")

print(f"Correct! It took {attempts} attempts.")`,
      description: "Combines random numbers with a while loop — a very common GCSE exam pattern."
    }
  ],
  keyPoints: [
    "Always import random at the top of your program before using it.",
    "random.randint(a, b) — random integer from a to b INCLUSIVE (both ends).",
    "random.choice(list) — picks one random item from a list.",
    "random.random() — returns a random float between 0.0 and 1.0.",
    "These are pseudo-random numbers — generated by an algorithm, not truly random.",
    "Common exam uses: dice games, password generators, quiz randomisation."
  ],
  commonMistakes: [
    { mistake: "Forgetting to import random before using it", fix: "Always put 'import random' at the top of your program." },
    { mistake: "Using random.randint(1, 6) and expecting 0-5", fix: "randint is INCLUSIVE of both ends: randint(1, 6) gives 1-6, not 0-5." },
    { mistake: "Calling random() without the module: random(1, 6)", fix: "Use random.randint(1, 6) — you need the module name prefix." }
  ],
  workedExample: {
    title: "Maths Quiz with Random Questions",
    problem: "Create a maths quiz that generates 5 random addition questions. Track the score and display the result at the end.",
    solution: "Use random.randint() to generate two numbers for each question, then check the user's answer.",
    code: `import random

score = 0

for i in range(5):
    a = random.randint(1, 20)
    b = random.randint(1, 20)
    answer = int(input(f"Q{i+1}: {a} + {b} = "))
    
    if answer == a + b:
        print("Correct!")
        score += 1
    else:
        print(f"Wrong! Answer was {a + b}")

print(f"You scored {score}/5")`
  },
  videoUrl: "https://www.youtube.com/embed/PqFKRqpHrjw",
  quiz: [
    { question: "What must you write at the top of your program to use random numbers?", options: ["use random", "import random", "#include random", "from random"], correctIndex: 1, explanation: "You must import the random module: import random.", hint: "Python uses the 'import' keyword to load modules.", difficulty: "easy" },
    { question: "What does random.randint(1, 10) return?", options: ["A float between 1.0 and 10.0", "An integer between 1 and 9", "An integer between 1 and 10 inclusive", "Always 1 or 10"], correctIndex: 2, explanation: "randint(1, 10) returns a random integer from 1 to 10, inclusive of both ends.", hint: "The 'int' in randint tells you the type. Both ends are included.", difficulty: "easy" },
    { question: "How do you pick a random item from a list called 'names'?", options: ["random.pick(names)", "random.choice(names)", "names.random()", "random(names)"], correctIndex: 1, explanation: "random.choice(list) picks one random element from the list.", hint: "The function name suggests making a selection.", difficulty: "easy" },
    { question: "Are Python's random numbers truly random?", options: ["Yes, completely random", "No, they are pseudo-random", "Only if you use a seed", "It depends on the OS"], correctIndex: 1, explanation: "Python generates pseudo-random numbers using an algorithm. They appear random but are deterministic.", hint: "There's a specific term for algorithm-generated 'randomness'.", difficulty: "medium" },
    { question: "What is the range of random.random() (no arguments)?", options: ["0 to 100", "1 to 10", "0.0 to 1.0", "-1.0 to 1.0"], correctIndex: 2, explanation: "random.random() returns a float between 0.0 (inclusive) and 1.0 (exclusive).", hint: "It returns a very small range of floating-point numbers.", difficulty: "medium" },
    { question: "OCR exam: To simulate a coin flip, which code is correct?", options: ["random.randint(0, 2)", "random.choice(['Heads', 'Tails'])", "random.coin()", "random.flip()"], correctIndex: 1, explanation: "random.choice(['Heads', 'Tails']) randomly picks one of the two options.", hint: "Which function picks from a list of options?", difficulty: "medium" }
  ]
};
