/**
 * Migration Drift Checker
 * ------------------------------------------------------------
 * Compares declared objects in `supabase/migrations/*.sql` against the
 * live schema mirror at `src/integrations/supabase/types.ts`
 * (auto-regenerated by Lovable after every applied migration).
 *
 * Detects:
 *   - CREATE TABLE [IF NOT EXISTS] public.<name>          → table must exist
 *   - ALTER TABLE public.<name> ADD COLUMN [IF NOT EXISTS] → column must exist
 *   - CREATE [OR REPLACE] FUNCTION public.<name>          → function must exist
 *
 * Triggers and RLS policies are intentionally ignored — they aren't
 * exposed in `types.ts`, so we can't detect them without DB access.
 *
 * Exit code: 0 = clean, 1 = drift detected.
 *
 * Run:    npx tsx scripts/checkMigrationDrift.ts
 */

import { readFileSync, readdirSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(process.cwd());
const MIGRATIONS_DIR = join(ROOT, "supabase", "migrations");
const TYPES_FILE = join(ROOT, "src", "integrations", "supabase", "types.ts");

type Declared = {
  kind: "table" | "column" | "function";
  table?: string;
  column?: string;
  name: string;
  file: string;
};

// ---------- Parse migrations ----------
function stripSqlComments(sql: string): string {
  // Remove -- line comments and /* ... */ block comments
  return sql
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/--.*$/gm, "");
}

function parseMigration(file: string, sql: string): Declared[] {
  const out: Declared[] = [];
  const cleaned = stripSqlComments(sql);

  // CREATE TABLE [IF NOT EXISTS] public.<name>
  const tableRe = /create\s+table\s+(?:if\s+not\s+exists\s+)?public\.([a-z_][a-z0-9_]*)/gi;
  for (const m of cleaned.matchAll(tableRe)) {
    out.push({ kind: "table", name: m[1].toLowerCase(), file });
  }

  // ALTER TABLE public.<table> ADD COLUMN [IF NOT EXISTS] <col>
  const colRe =
    /alter\s+table\s+(?:if\s+exists\s+)?public\.([a-z_][a-z0-9_]*)\s+add\s+column\s+(?:if\s+not\s+exists\s+)?([a-z_][a-z0-9_]*)/gi;
  for (const m of cleaned.matchAll(colRe)) {
    out.push({
      kind: "column",
      table: m[1].toLowerCase(),
      column: m[2].toLowerCase(),
      name: `${m[1].toLowerCase()}.${m[2].toLowerCase()}`,
      file,
    });
  }

  // CREATE [OR REPLACE] FUNCTION public.<name>
  const fnRe = /create\s+(?:or\s+replace\s+)?function\s+public\.([a-z_][a-z0-9_]*)/gi;
  for (const m of cleaned.matchAll(fnRe)) {
    out.push({ kind: "function", name: m[1].toLowerCase(), file });
  }

  return out;
}

// ---------- Parse types.ts ----------
function extractBlock(src: string, header: RegExp): string | null {
  const m = src.match(header);
  if (!m) return null;
  const start = m.index! + m[0].length;
  let depth = 1;
  let i = start;
  while (i < src.length && depth > 0) {
    const ch = src[i];
    if (ch === "{") depth++;
    else if (ch === "}") depth--;
    i++;
  }
  return depth === 0 ? src.slice(start, i - 1) : null;
}

function parseTypes(src: string): {
  tables: Map<string, Set<string>>;
  functions: Set<string>;
} {
  const tables = new Map<string, Set<string>>();
  const functions = new Set<string>();

  // Find: public: { Tables: { ... } Functions: { ... } }
  const publicBlock = extractBlock(src, /public\s*:\s*\{/);
  if (!publicBlock) return { tables, functions };

  const tablesBlock = extractBlock(publicBlock, /Tables\s*:\s*\{/);
  if (tablesBlock) {
    // Each table: <name>: { Row: { ... }, Insert: { ... }, ... }
    // Parse top-level keys at depth 1.
    let i = 0;
    let depth = 0;
    while (i < tablesBlock.length) {
      const ch = tablesBlock[i];
      if (ch === "{") depth++;
      else if (ch === "}") depth--;
      else if (depth === 0) {
        const tableMatch = tablesBlock.slice(i).match(/^\s*([a-z_][a-z0-9_]*)\s*:\s*\{/i);
        if (tableMatch) {
          const tableName = tableMatch[1].toLowerCase();
          const tableBody = extractBlock(tablesBlock.slice(i), /\{/);
          if (tableBody) {
            const rowBody = extractBlock(tableBody, /Row\s*:\s*\{/);
            const cols = new Set<string>();
            if (rowBody) {
              for (const cm of rowBody.matchAll(/^\s*([a-z_][a-z0-9_]*)\s*:/gim)) {
                cols.add(cm[1].toLowerCase());
              }
            }
            tables.set(tableName, cols);
            // Skip past the table block
            i += tableMatch[0].length;
            depth = 1;
            while (i < tablesBlock.length && depth > 0) {
              const c2 = tablesBlock[i];
              if (c2 === "{") depth++;
              else if (c2 === "}") depth--;
              i++;
            }
            continue;
          }
        }
      }
      i++;
    }
  }

  const functionsBlock = extractBlock(publicBlock, /Functions\s*:\s*\{/);
  if (functionsBlock) {
    for (const fm of functionsBlock.matchAll(/^\s*([a-z_][a-z0-9_]*)\s*:\s*\{/gim)) {
      functions.add(fm[1].toLowerCase());
    }
  }

  return { tables, functions };
}

// ---------- Run ----------
function main() {
  let migFiles: string[];
  try {
    migFiles = readdirSync(MIGRATIONS_DIR)
      .filter((f) => f.endsWith(".sql"))
      .sort();
  } catch (err) {
    console.error(`✗ Could not read migrations dir: ${MIGRATIONS_DIR}`);
    process.exit(1);
  }

  const declared: Declared[] = [];
  for (const f of migFiles) {
    const sql = readFileSync(join(MIGRATIONS_DIR, f), "utf8");
    declared.push(...parseMigration(f, sql));
  }

  const typesSrc = readFileSync(TYPES_FILE, "utf8");
  const { tables, functions } = parseTypes(typesSrc);

  const drift: { msg: string; file: string }[] = [];

  for (const d of declared) {
    if (d.kind === "table") {
      if (!tables.has(d.name)) {
        drift.push({
          file: d.file,
          msg: `table "public.${d.name}" declared in ${d.file} is missing from live schema (types.ts)`,
        });
      }
    } else if (d.kind === "column") {
      const cols = tables.get(d.table!);
      if (!cols) {
        drift.push({
          file: d.file,
          msg: `column "${d.table}.${d.column}" declared in ${d.file} — parent table missing from live schema`,
        });
      } else if (!cols.has(d.column!)) {
        drift.push({
          file: d.file,
          msg: `column "public.${d.table}.${d.column}" declared in ${d.file} is missing from live schema (types.ts)`,
        });
      }
    } else if (d.kind === "function") {
      if (!functions.has(d.name)) {
        drift.push({
          file: d.file,
          msg: `function "public.${d.name}()" declared in ${d.file} is missing from live schema (types.ts)`,
        });
      }
    }
  }

  // Report
  const counts = declared.reduce(
    (acc, d) => ((acc[d.kind] = (acc[d.kind] ?? 0) + 1), acc),
    {} as Record<string, number>,
  );

  console.log(`\nMigration drift check`);
  console.log(`─────────────────────`);
  console.log(`Migrations scanned: ${migFiles.length}`);
  console.log(
    `Declared objects:   ${counts.table ?? 0} tables · ${counts.column ?? 0} columns · ${counts.function ?? 0} functions`,
  );
  console.log(`Live schema:        ${tables.size} tables · ${functions.size} functions\n`);

  if (drift.length === 0) {
    console.log(`✓ No drift — every declared table/column/function exists in the live schema.\n`);
    process.exit(0);
  }

  console.error(`✗ Drift detected (${drift.length} issue${drift.length === 1 ? "" : "s"}):\n`);
  for (const d of drift) {
    console.error(`  · ${d.msg}`);
  }
  console.error(
    `\nFix: ensure the listed migration(s) have been applied to the live database, then regenerate types.ts.\n`,
  );
  process.exit(1);
}

main();
