// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const _rawUrl = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_URL = _rawUrl.startsWith("http") ? _rawUrl : "https://eneaikataseigolavizw.supabase.co";
const _rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "";
const SUPABASE_PUBLISHABLE_KEY = _rawKey || "sb_publishable_TL1mLqQ1LifZ5RS3jkuDGQ_viis5qYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
